[talk]
title = "Build Systems, Package Managers, pyproject.toml and you - how to work with Python in 2023"
speaker = "Jonathan Daniel"
language = "English"
location = "Main hall"
start = 2023-07-04 16:00:00
url = "https://cfp.pycon.org.il/conference2023/talk/DEZUBS/"

[talk.duration]
value = 20
unit = "minute"
